[colors.bright]
black = "#7a8181"
cyan = "#2383d1"
green = "#49d0c5"
magenta = "#697098"
red = "#f76e6e"
white = "#989fb1"
yellow = "#dac26b"

[colors.cursor]
cursor = "#403f53"
text = "#fbfbfb"

[colors.normal]
black = "#011627"
blue = "#336FD8"
cyan = "#2383d1"
green = "#2aa298"
magenta = "#403f53"
red = "#d3423e"
white = "#7a8181"
yellow = "#daaa01"

[colors.primary]
background = "#FFFFFF"
foreground = "#000000"

[colors.selection]
background = "#f2f2f2"
text = "#403f53"

[font]
size = 12

[font.normal]
family = "CaskaydiaCove Nerd Font"

# [schemes.night_owlish_light.bright]
# black = "#7a8181"
# cyan = "#2383d1"
# green = "#49d0c5"
# magenta = "#697098"
# red = "#f76e6e"
# white = "#989fb1"
# yellow = "#dac26b"
# 
# [schemes.night_owlish_light.cursor]
# cursor = "#403f53"
# text = "#fbfbfb"
# 
# [schemes.night_owlish_light.normal]
# black = "#011627"
# blue = "#336FD8"
# cyan = "#2383d1"
# green = "#2aa298"
# magenta = "#403f53"
# red = "#d3423e"
# white = "#7a8181"
# yellow = "#daaa01"
# 
# [schemes.night_owlish_light.primary]
# background = "#FFFFFF"
# foreground = "#000000"
# 
# [schemes.night_owlish_light.selection]
# background = "#f2f2f2"
# text = "#403f53"
